# LORDSHIPWEATHER.UK docker image (weewx-docker)
# Copied from felddy/weewx
# last updated 31/03/2023 - to install garagepi versions on a debian system, using slim debian for target

#==== INSTALL-WEEWX-STAGE =====

# Can safely use a full debian system (with least restrictions) for the initial-stage, as it is discarded for the final-stage

FROM python:3.10.10-bullseye as install-weewx-stage
# was FROM python:3.10.7-alpine3.15 as install-weewx-stage

# ARG definitions

ARG BUILDPLATFORM
ARG TARGETPLATFORM
ARG WEEWX_UID=421
ARG WEEWX_HOME="/home/weewx"
ARG WEEWX_VERSION="4.5.1"
ARG ARCHIVE="weewx-${WEEWX_VERSION}.tar.gz"

RUN echo "Dockerfile initialising on $BUILDPLATFORM, building for $TARGETPLATFORM" && \
	apt-get -qy install wget

WORKDIR /tmp
COPY src/hashes requirements.txt ./

# Download extension sources and verify hashes; -nv to give non-verbose output

RUN wget -nv -O "${ARCHIVE}" "https://weewx.com/downloads/released_versions/${ARCHIVE}" && \
    wget -nv -O weewx-interceptor.zip https://github.com/matthewwall/weewx-interceptor/archive/master.zip && \
    wget -nv -O weewx-mqtt.zip https://github.com/matthewwall/weewx-mqtt/archive/master.zip && \
    wget -nv -O weewx-belchertown.tar.gz https://github.com/poblabs/weewx-belchertown/releases/download/weewx-belchertown-1.2/weewx-belchertown-release-1.2.tar.gz && \
	sha256sum -c < hashes

# WeeWX setup

RUN addgroup --system --gid ${WEEWX_UID} weewx && \
	adduser --system --uid ${WEEWX_UID} --ingroup weewx weewx && \
	tar --extract --gunzip --directory ${WEEWX_HOME} --strip-components=1 --file "${ARCHIVE}" && \
	chown -R weewx:weewx ${WEEWX_HOME}

# Setup Python and dependencies for Weewx, using pep517 to avoid use of legacy setup warnings

RUN python -m venv /opt/venv && \
	pip install --upgrade pip
COPY ./requirements.txt /usr/src/app
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --use-pep517 -Ur requirements.txt	#--use-pep517 to avoid legacy warning

# Install extensions

WORKDIR ${WEEWX_HOME}
RUN bin/wee_extension --install /tmp/weewx-mqtt.zip && \
	bin/wee_extension --install /tmp/weewx-interceptor.zip && \
	bin/wee_extension --install /tmp/weewx-belchertown.tar.gz
COPY src/entrypoint.sh src/version.txt ./

# ===== FINAL-STAGE ====

FROM python:3.10.10-slim-bullseye as final-stage
# latest is 3.12.0a5.-slim-bullseye

# ARG & ENV definitions

ARG WEEWX_UID=421
ARG WEEWX_HOME="/home/weewx"
ARG WEEWX_VERSION="4.5.1"
ARG OS_LOCALE="/usr/lib/locale/locale-archive"
ENV TZ="Europe/London"

# Not sure whether these label definitions are required, copied from original dockerfile

# For a list of pre-defined annotation keys and value types see:
# https://github.com/opencontainers/image-spec/blob/master/annotations.md
# Note: Additional labels are added by the build workflow.
# LABEL org.opencontainers.image.authors="markf+github@geekpad.com"
# LABEL org.opencontainers.image.vendor="Geekpad"
# LABEL com.weewx.version=${WEEWX_VERSION}

# Create new user and group for weewx in final-stage

RUN addgroup --system --gid ${WEEWX_UID} weewx && \
	adduser --system --uid ${WEEWX_UID} --ingroup weewx weewx

# install required packages for target system

RUN apt-get update && apt-get install -qy libusb-1.0-0 gosu busybox-syslogd tzdata nano

# Copy key files set up in install-weewx-stage

WORKDIR ${WEEWX_HOME}
COPY --from=install-weewx-stage /opt/venv /opt/venv
COPY --from=install-weewx-stage ${WEEWX_HOME} ${WEEWX_HOME}

# Set Locale and TimeZone - best to use explicit form of en_GB.UTF-8, rather than OS-LOCALE

RUN apt-get update && \
	apt-get install -qy apt-utils locales && \
	echo "en_GB.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen en_GB.UTF-8	locale
ENV LANG en_GB.UTF-8

# create the data volume for binding to host folders (in /opt/weewx)

RUN mkdir -p /data
VOLUME ["/data"]

# set PATH variables and start the container

ENV PATH="/opt/venv/bin:$PATH"
ENV PATH="/data/bin:$PATH"
ENTRYPOINT ["./entrypoint.sh"]
CMD ["/data/weewx.conf"]
